import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  Alert,
  TextInput,
  TouchableOpacity,
  Platform,
} from "react-native";
import Slider from "@react-native-community/slider";
import { colors, textStyles } from "../utils/theme";
import { Picker } from "@react-native-picker/picker";
import { useResponsive } from "../utils/useResponsive";

type Step1AcknowledgeProps = {
  selectedEmotion: string;
  setSelectedEmotion: (emotion: string) => void;
  initialRating: number;
  setInitialRating: (rating: number) => void;
};

const Step1Acknowledge = ({
  selectedEmotion,
  setSelectedEmotion,
  initialRating,
  setInitialRating,
}: Step1AcknowledgeProps) => {
  // Use responsive hook instead of local state
  const { isMobile, isTablet, isDesktop } = useResponsive();

  const [inputMethod, setInputMethod] = useState<"dropdown" | "text" | null>(
    null,
  );

  // Emotions array for dropdown
  const emotions = [
    "",
    "Sad",
    "Mad",
    "Scared",
    "Anxious",
    "Overwhelmed",
    "Resentful",
    "Shame",
    "Fear",
    "Terrified",
    "Out of Control",
    "Unsafe",
  ];

  // Shared styling for all input elements
  const getInputStyle = () => ({
    flex: 1,
    backgroundColor: colors.lightGray,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    height: isMobile ? 44 : isTablet ? 48 : 52,
    paddingHorizontal: isMobile ? 10 : 12,
    fontSize: isMobile ? 12 : isTablet ? 14 : 16,
    color: colors.secondary,
    fontFamily: "PoiretOne",
    letterSpacing: 1.5,
  });

  const styles = StyleSheet.create({
    container: {
      alignItems: "center",
      paddingHorizontal: isMobile ? "5%" : isTablet ? "8%" : "10%",
      paddingVertical: isMobile ? "5%" : isTablet ? "8%" : "1%",
    },
    title: {
      fontSize: isMobile ? 18 : 20,
      fontWeight: "bold",
      color: colors.secondary,
      textAlign: "center",
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "1.5%",
      ...textStyles.header,
    },

    subtitle: {
      fontSize: isMobile ? 16 : isTablet ? 18 : 20,
      color: colors.secondary,
      marginTop: isMobile ? "3%" : isTablet ? "2%" : "1.5%",
      marginBottom: isMobile ? ".25%" : isTablet ? ".25%" : ".5%",
      textAlign: "center",
      ...textStyles.body,
    },
    sliderContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      maxWidth: 500,
      marginVertical: isMobile ? "3%" : isTablet ? "3%" : ".25%",
    },
    emotions: {
      fontSize: isMobile ? 14 : isTablet ? 12 : 16,
      ...textStyles.header,
      paddingHorizontal: isMobile ? "2%" : "3%",
      color: colors.secondary,
    },
    slider: {
      flex: 1,
      height: 40,
    },
    ratingText: {
      fontSize: isMobile ? 12 : isTablet ? 14 : 18,
      color: colors.secondary,
      marginTop: isMobile ? ".5%" : isTablet ? ".5%" : ".5%",
      ...textStyles.body,
    },
    introText: {
      fontSize: isMobile ? 12 : isTablet ? 16 : 22,
      color: colors.secondary,
      textAlign: "center",
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "2%",
      ...textStyles.body,
    },
    emotionInputRow: {
      flexDirection: isMobile ? "column" : "row",
      gap: isMobile ? 8 : isTablet ? 10 : 12,
      width: "100%",
      maxWidth: 500,
      marginBottom: isMobile ? "2%" : isTablet ? "2%" : ".25%",
    },
    pickerContainer: {
      flex: 1,
      backgroundColor: colors.lightGray,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      height: isMobile ? 44 : isTablet ? 48 : 52,
      justifyContent: "center",
      ...textStyles.body,
    },
    textInput: {
      ...getInputStyle(),
      textTransform: "uppercase" as const,
      textAlign: "center",
    },
    voiceButton: {
      width: isMobile ? "100%" : 44,
      height: isMobile ? 44 : isTablet ? 48 : 52,
      backgroundColor: colors.slateBlue,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    voiceButtonText: {
      fontSize: isMobile ? 18 : isTablet ? 20 : 22,
    },
    autoGeneratedText: {
      fontSize: isMobile ? 12 : isTablet ? 18 : 22,
      color: colors.secondary,
      marginTop: isMobile ? "4%" : isTablet ? "3%" : "2%",
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "2%",
      ...textStyles.body,
    },
    breathingPrompt: {
      fontSize: isMobile ? 14 : isTablet ? 16 : 20,
      color: colors.secondary,
      textAlign: "center",
      marginTop: isMobile ? "4%" : isTablet ? "2%" : "1%",
      ...textStyles.body,
    },
    clearButton: {
      backgroundColor: colors.mutedTeal,
      padding: isMobile ? 10 : 10,
      borderRadius: 8,
      minWidth: isMobile ? 80 : 60,
      alignItems: "center",
      marginTop: 10,
      boxShadow: "0px 2px 3.84px rgba(0, 0, 0, 0.25)",
      elevation: 5,
    },
    clearButtonText: {
      color: colors.white,
      fontSize: isMobile ? 14 : 14,
      fontWeight: "600",
      ...textStyles.header,
    },
  });

  return (
    <View style={styles.container}>
      {/* Step title */}
      <Text style={styles.title}>
        Step 1: I Acknowledge My Emotions Non-Judgmentally
      </Text>
      <Text style={styles.introText}>
        By using the word "interesting" or by using phrases such as I feel
      </Text>
      <View style={styles.emotionInputRow}>
        {/* Show dropdown only when no input method chosen or dropdown was used */}
        {(inputMethod === null || inputMethod === "dropdown") && (
          <>
            {Platform.OS === "web" ? (
              <select
                value={selectedEmotion}
                onChange={e => {
                  setSelectedEmotion(e.target.value);
                  setInputMethod("dropdown");
                }}
                style={{
                  ...getInputStyle(),
                  textTransform: "uppercase",
                  borderStyle: "solid",
                  outline: "none",
                  textAlign: "center",
                  color: colors.secondary,
                }}
              >
                {emotions.map((emotion, index) => (
                  <option
                    key={index}
                    value={emotion}
                    style={{
                      color: colors.secondary,
                      backgroundColor: colors.lightGray,
                      fontFamily: "PoiretOne",
                      textTransform: "uppercase",
                    }}
                  >
                    {emotion || "Select emotion..."}
                  </option>
                ))}
              </select>
            ) : (
              <View style={styles.pickerContainer}>
                <Picker
                  selectedValue={selectedEmotion}
                  onValueChange={value => {
                    setSelectedEmotion(value);
                    setInputMethod("dropdown");
                  }}
                >
                  {emotions.map((emotion, index) => (
                    <Picker.Item
                      key={index}
                      label={emotion || "Select emotion..."}
                      value={emotion}
                    />
                  ))}
                </Picker>
              </View>
            )}
          </>
        )}

        {/* Show text input only when no input method chosen or text was used */}
        {(inputMethod === null || inputMethod === "text") && (
          <TextInput
            style={styles.textInput}
            value={selectedEmotion}
            onChangeText={value => {
              setSelectedEmotion(value);
              setInputMethod("text");
            }}
            placeholder="Or type emotion..."
            placeholderTextColor={colors.mediumGray}
            onSubmitEditing={() => setInputMethod("text")}
          />
        )}

        {/* Voice button always visible */}
        <TouchableOpacity
          style={styles.voiceButton}
          onPress={() => Alert.alert("Voice Input", "Voice input coming soon!")}
        >
          <Text style={styles.voiceButtonText}>🎤</Text>
        </TouchableOpacity>
      </View>

      {selectedEmotion && (
        <Text style={styles.autoGeneratedText}>
          I feel {selectedEmotion}. Isn't that interesting how {selectedEmotion}{" "}
          I feel?
        </Text>
      )}
      {selectedEmotion !== "" && (
        <TouchableOpacity
          style={styles.clearButton}
          onPress={() => {
            setSelectedEmotion("");
            setInputMethod(null);
          }}
        >
          <Text style={styles.clearButtonText}>Clear Emotion</Text>
        </TouchableOpacity>
      )}
      {/* Rating question */}
      <Text style={styles.subtitle}>At what level are your Emotions?</Text>

      {/* Slider  */}
      <View style={styles.sliderContainer}>
        <Text style={styles.emotions}>Calm</Text>
        <Slider
          value={initialRating}
          onValueChange={setInitialRating}
          minimumValue={0}
          maximumValue={10}
          step={1}
          style={styles.slider}
          minimumTrackTintColor={colors.secondary}
          maximumTrackTintColor={colors.primary}
          thumbTintColor={colors.mutedTeal}
        />
        <Text style={styles.emotions}>Unbearable</Text>
      </View>

      {/* Display current rating */}
      <Text style={styles.ratingText}>
        Rating: {Math.round(initialRating)}/10
      </Text>
      {/* Breathing prompt */}
      <Text style={styles.breathingPrompt}>
        AND then I breathe in deeply and slowly (diaphragmatically) and release
        the air SLOWLY.
      </Text>
    </View>
  );
};

export default Step1Acknowledge;
