import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  Dimensions,
  Alert,
  TextInput,
  TouchableOpacity,
  Platform,
} from "react-native";
import Slider from "@react-native-community/slider";
import { colors, textStyles } from "../utils/theme";
import { Picker } from "@react-native-picker/picker";

const Step1Acknowledge = ({
  selectedEmotion,
  setSelectedEmotion,
  initialRating,
  setInitialRating,
}: any) => {
  // Screen dimensions with state for responsive updates
  const [screenWidth, setScreenWidth] = useState(
    Dimensions.get("window").width
  );

  // Listen for screen size changes
  useEffect(() => {
    const subscription = Dimensions.addEventListener("change", ({ window }) => {
      setScreenWidth(window.width);
    });

    return () => subscription?.remove();
  }, []);

  // Responsive breakpoints
  const isMobile = screenWidth < 375;
  const isTablet = screenWidth >= 375 && screenWidth < 768;
  const isDesktop = screenWidth >= 768;

  // emtions array for dropdown
  const emotions = [
    "",
    "Sad",
    "Mad",
    "Scared",
    "Anxious",
    "Overwhelmed",
    "Resentful",
    "Shame",
    "Fear",
    "Terrified",
    "Out of Control",
    "Unsafe",
  ];

  const styles = StyleSheet.create({
    container: {
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: isMobile ? "5%" : isTablet ? "8%" : "10%",
      paddingVertical: isMobile ? "22%" : isTablet ? "18%" : "5%",
    },
    title: {
      fontSize: isMobile ? 16 : isTablet ? 22 : 32,
      fontWeight: "bold",
      color: colors.secondary,
      textAlign: "center",
      marginBottom: isMobile ? "6%" : isTablet ? "3%" : "1.5%",
      ...textStyles.body,
    },
    subtitle: {
      fontSize: isMobile ? 14 : isTablet ? 18 : 28,
      color: colors.secondary,
      marginBottom: isMobile ? "4%" : isTablet ? "2%" : "2%",
      textAlign: "center",
      ...textStyles.body,
    },
    sliderContainer: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      maxWidth: 500,
      marginVertical: isMobile ? "3%" : isTablet ? "3%" : ".25%",
    },
    emotions: {
      fontSize: isMobile ? 10 : isTablet ? 12 : 16,
      ...textStyles.header,
      paddingHorizontal: isMobile ? "2%" : "3%",
      color: colors.secondary,
    },
    slider: {
      flex: 1,
      height: 40,
    },
    ratingText: {
      fontSize: isMobile ? 12 : isTablet ? 14 : 18,
      color: colors.secondary,
      marginTop: isMobile ? "1%" : isTablet ? "2%" : "1%",
      ...textStyles.body,
    },
    introText: {
      fontSize: isMobile ? 12 : isTablet ? 16 : 22,
      color: colors.secondary,
      textAlign: "center",
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "2%",
      ...textStyles.body,
    },
    emotionInputRow: {
      flexDirection: "row",
      gap: isMobile ? 8 : isTablet ? 10 : 12,
      width: "100%",
      maxWidth: 500,
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "2%",
    },
    pickerContainer: {
      flex: 1,
      backgroundColor: colors.lightGray,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      height: isMobile ? 44 : isTablet ? 48 : 52,
      justifyContent: "center",
    },
    textInput: {
      flex: 1,
      backgroundColor: colors.lightGray,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      height: isMobile ? 44 : isTablet ? 48 : 52,
      paddingHorizontal: isMobile ? 10 : 12,
      fontSize: isMobile ? 12 : isTablet ? 14 : 16,
      color: colors.secondary,
      ...textStyles.body,
    },
    voiceButton: {
      width: 44,
      height: isMobile ? 44 : isTablet ? 48 : 52,
      backgroundColor: colors.slateBlue,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    voiceButtonText: {
      fontSize: isMobile ? 18 : isTablet ? 20 : 22,
    },
    autoGeneratedText: {
      fontSize: isMobile ? 12 : isTablet ? 14 : 16,
      color: colors.secondary,
      textAlign: "center",
      marginTop: isMobile ? "4%" : isTablet ? "3%" : "2%",
      marginBottom: isMobile ? "4%" : isTablet ? "3%" : "2%",
      ...textStyles.body,
    },
    breathingPrompt: {
      fontSize: isMobile ? 14 : isTablet ? 16 : 18,
      color: colors.secondary,
      textAlign: "center",
      marginTop: isMobile ? "6%" : isTablet ? "5%" : "4%",
      ...textStyles.body,
    },
  });

  return (
    <View style={styles.container}>
      {/* Step title */}
      <Text style={styles.title}>
        Step 1: Acknowledge my emotions non-judgmentally
      </Text>
      <Text style={styles.introText}>
        By using the word "interesting" using phrases such as I feel
      </Text>
      <View style={styles.emotionInputRow}>
        {/* Picker - platform specific */}
        {Platform.OS === "web" ? (
          <select
            value={selectedEmotion}
            onChange={e => setSelectedEmotion(e.target.value)}
          >
            {emotions.map((emotion, index) => (
              <option key={index} value={emotion}>
                {emotion || "Select emotion..."}
              </option>
            ))}
          </select>
        ) : (
          /*  mobile */
          <View style={styles.pickerContainer}>
            <Picker
              selectedValue={selectedEmotion}
              onValueChange={value => setSelectedEmotion(value)}
            >
              {emotions.map((emotion, index) => (
                <Picker.Item
                  key={index}
                  label={emotion || "Select emotion..."}
                  value={emotion}
                />
              ))}
            </Picker>
          </View>
        )}
      </View>

      {/* Rating question */}
      <Text style={styles.subtitle}>At what level are your Emotions?</Text>

      {/* Slider  */}
      <View style={styles.sliderContainer}>
        <Text style={styles.emotions}>Calm</Text>
        <Slider
          value={initialRating}
          onValueChange={setInitialRating}
          minimumValue={0}
          maximumValue={10}
          step={1}
          style={styles.slider}
          minimumTrackTintColor={colors.secondary}
          maximumTrackTintColor={colors.primary}
          thumbTintColor={colors.mutedTeal}
        />
        <Text style={styles.emotions}>Unbearable</Text>
      </View>

      {/* Display current rating */}
      <Text style={styles.ratingText}>
        Rating: {Math.round(initialRating)}/10
      </Text>
    </View>
  );
};

export default Step1Acknowledge;
